version: '3.11'
services:
  backend:
    build: ./DroneHub
    command: gunicorn DroneHub.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./DroneHub:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=host.docker.internal  # Docker'dan yerel makineye erişim için
      - DB_NAME=dronehubdb
      - DB_USER=postgres
      - DB_PASSWORD=3357
      - DB_PORT=5432

  frontend:
    build: ./drone-hub-frontend
    volumes:
      - ./drone-hub-frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8000
